spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  # Email configuration for production
  mail:
    host: ${SPRING_MAIL_HOST:${MAIL_HOST:smtp.gmail.com}}
    port: ${SPRING_MAIL_PORT:${MAIL_PORT:587}}
    username: ${MAIL_USERNAME:${SPRING_MAIL_USERNAME:}}
    password: ${MAIL_PASSWORD:${SPRING_MAIL_PASSWORD:}}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, email, profile]
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/google

# Application configuration
app:
  base-url: ${APP_BASE_URL:https://your-app.onrender.com}
  upload:
    dir: ${UPLOAD_DIR:/tmp/uploads}
    max-file-size: 5MB
    max-request-size: 5MB

# Logging for production
logging:
  level:
    org.hibernate.SQL: WARN
    org.springframework.security: INFO
    com.example.booking: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server configuration
server:
  port: ${PORT:8081}
  error:
    include-message: never
    include-binding-errors: never 