# ===== Spring Boot PROD config for Render =====
# YÊU CẦU: đặt các biến môi trường trong Render Dashboard:
#   JDBC_DATABASE_URL=jdbc:postgresql://dpg-d37uh8ruibrs739c7sf0-a:5432/bookeat_db?sslmode=require
#   JDBC_DATABASE_USERNAME=bookeat_user
#   JDBC_DATABASE_PASSWORD=58IJhzpjEobFFUmJ762dmkEdSLPPRbZX
# (Nếu chạy ngoài Render, dùng external host và cùng tham số sslmode=require)

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Hibernate tự detect PostgreSQLDialect, nên không cần set thủ công
        format_sql: false
    show-sql: false

  # Email configuration for production
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, email, profile]
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/google

# Application configuration
app:
  base-url: ${APP_BASE_URL:https://your-app.onrender.com}
  upload:
    dir: ${UPLOAD_DIR:/tmp/uploads}
    max-file-size: 5MB
    max-request-size: 5MB

# Logging for production
logging:
  level:
    org.hibernate.SQL: WARN
    org.springframework.security: INFO
    com.example.booking: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server configuration
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
