# ===== Spring Boot PROD config (Render) =====
# Cách dùng biến môi trường (ưu tiên):
#  - JDBC_DATABASE_URL     (chuỗi JDBC đầy đủ)
#  - JDBC_DATABASE_USERNAME
#  - JDBC_DATABASE_PASSWORD
#
# Nếu bạn CHƯA set biến, YAML bên dưới có fallback sang External URL của bạn.

spring:
  datasource:
    # ƯU TIÊN: lấy từ JDBC_DATABASE_URL nếu có; nếu không, lấy từ DATABASE_URL;
    # cuối cùng fallback sang giá trị cố định của bạn (External host + sslmode=require)
    url: ${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://dpg-d37uh8ruibrs739c7sf0-a.singapore-postgres.render.com:5432/bookeat_db?sslmode=require}}
    username: ${JDBC_DATABASE_USERNAME:${DB_USERNAME:bookeat_user}}
    password: ${JDBC_DATABASE_PASSWORD:${DB_PASSWORD:58IJhzpjEobFFUmJ762dmkEdSLPPRbZX}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    # Đặt dialect tường minh để tránh lỗi khi chưa lấy được JDBC metadata
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Email (tuỳ chọn)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, email, profile]
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/google

# App config
app:
  base-url: ${APP_BASE_URL:https://your-app.onrender.com}
  upload:
    dir: ${UPLOAD_DIR:/tmp/uploads}
    max-file-size: 5MB
    max-request-size: 5MB

# Logging
logging:
  level:
    org.hibernate.SQL: WARN
    org.springframework.security: INFO
    com.example.booking: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
