-- THE GRILL - COMPLETE PLAYBOOK
-- Run in pgAdmin/psql

\echo ===== PART 1: Create restaurant and owner =====
\i scripts/add_the_grill_restaurant.sql

\echo ===== PART 2: Insert images (after upload) =====
-- After running the Python uploader, uncomment the next line:
-- \i scripts/insert_the_grill_images.sql

\echo ===== PART 3: Add dishes, tables, services =====
\i scripts/add_the_grill_tables_dishes_services.sql

\echo ===== PART 4: Verify =====
SELECT 'RESTAURANT' AS section, rp.restaurant_id, rp.restaurant_name, rp.approval_status
FROM restaurant_profile rp
WHERE rp.restaurant_name = 'The Grill'
ORDER BY rp.created_at DESC
LIMIT 1;

SELECT 'DISHES' AS section, COUNT(*) AS total
FROM dish
WHERE restaurant_id = (SELECT restaurant_id FROM restaurant_profile WHERE restaurant_name = 'The Grill' ORDER BY created_at DESC LIMIT 1);

SELECT 'TABLES' AS section, COUNT(*) AS total
FROM restaurant_table
WHERE restaurant_id = (SELECT restaurant_id FROM restaurant_profile WHERE restaurant_name = 'The Grill' ORDER BY created_at DESC LIMIT 1);

SELECT 'SERVICES' AS section, COUNT(*) AS total
FROM restaurant_service
WHERE restaurant_id = (SELECT restaurant_id FROM restaurant_profile WHERE restaurant_name = 'The Grill' ORDER BY created_at DESC LIMIT 1);

-- ===============================================
-- THE GRILL - ONE-SHOT SQL PLAYBOOK (pgAdmin/psql)
-- ===============================================
-- This file guides you through adding The Grill end-to-end.
-- Run PART 1 first, then upload images (Python), then PART 2, PART 3, PART 4.

-- =================
-- PART 1 - CREATE
-- =================
-- Creates/attaches owner (user 'Taiphan') and inserts restaurant_profile (APPROVED)
\echo ===== PART 1: Create restaurant and owner =====
\i scripts/add_the_grill_restaurant.sql

-- =====================
-- PART 2 - INSERT IMAGES
-- =====================
-- After you run the Python uploader, this file is generated automatically.
-- If not yet generated, skip and come back later.
\echo ===== PART 2: Insert images (generated by Python) =====
-- Uncomment the next line after upload_the_grill.py generated the file:
-- \i scripts/insert_the_grill_images.sql

-- ===================================
-- PART 3 - MENU, TABLES, EXTRA SERVICES
-- ===================================
-- This block auto-detects restaurant_id by name = 'The Grill'.
\echo ===== PART 3: Add dishes, tables, services =====
\i scripts/add_the_grill_menu_tables_services.sql

-- ==================
-- PART 4 - VERIFY
-- ==================
\echo ===== PART 4: Verification =====
SELECT 'RESTAURANT' AS section, rp.restaurant_id, rp.restaurant_name, rp.approval_status
FROM restaurant_profile rp
WHERE rp.restaurant_name = 'The Grill'
ORDER BY rp.created_at DESC
LIMIT 1;

SELECT 'DISHES' AS section, COUNT(*) AS total
FROM dish
WHERE restaurant_id = (SELECT restaurant_id FROM restaurant_profile WHERE restaurant_name = 'The Grill' ORDER BY created_at DESC LIMIT 1);

SELECT 'TABLES' AS section, COUNT(*) AS total
FROM restaurant_table
WHERE restaurant_id = (SELECT restaurant_id FROM restaurant_profile WHERE restaurant_name = 'The Grill' ORDER BY created_at DESC LIMIT 1);

SELECT 'SERVICES' AS section, COUNT(*) AS total
FROM restaurant_service
WHERE restaurant_id = (SELECT restaurant_id FROM restaurant_profile WHERE restaurant_name = 'The Grill' ORDER BY created_at DESC LIMIT 1);


