import argparse
import os
import sys
from pathlib import Path

"""
Upload images for 'The Grill' to Cloudinary and generate insert_the_grill_images.sql.

Usage (Windows PowerShell from repo root):
  python scripts\\upload_the_grill_images.py <RESTAURANT_ID> "Media_update\\The Grill - Hoà Hải, Ngũ Hành Sơn, Đà Nẵng"

Auth:
- Prefer CLOUDINARY_URL env var, e.g. cloudinary://<api_key>:<api_secret>@<cloud_name>
- Or set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
"""

SUPPORTED_EXTS = {".webp", ".jpg", ".jpeg", ".png"}

def get_cloudinary():
    try:
        import cloudinary
        import cloudinary.uploader
        import cloudinary.api
    except ImportError:
        print("Please install cloudinary: pip install cloudinary", file=sys.stderr)
        raise

    cloudinary_url = os.getenv("CLOUDINARY_URL")
    if cloudinary_url:
        cloudinary.config(cloudinary_url=cloudinary_url)
    else:
        cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME")
        api_key = os.getenv("CLOUDINARY_API_KEY")
        api_secret = os.getenv("CLOUDINARY_API_SECRET")
        if not (cloud_name and api_key and api_secret):
            raise RuntimeError("Cloudinary credentials missing. Set CLOUDINARY_URL or CLOUDINARY_CLOUD_NAME/API_KEY/API_SECRET")
        cloudinary.config(cloud_name=cloud_name, api_key=api_key, api_secret=api_secret, secure=True)

    return cloudinary

def collect_images(folder: Path):
    return [p for p in sorted(folder.iterdir(), key=lambda x: x.name) if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS]

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("restaurant_id", type=int, help="restaurant_profile.restaurant_id")
    parser.add_argument("images_folder", type=str, help="Folder containing images for The Grill")
    args = parser.parse_args()

    folder = Path(args.images_folder)
    if not folder.exists():
        print(f"Images folder not found: {folder}", file=sys.stderr)
        sys.exit(1)

    cloudinary = get_cloudinary()
    images = collect_images(folder)
    if not images:
        print(f"No images found in {folder}", file=sys.stderr)
        sys.exit(1)

    print(f"Uploading {len(images)} images from {folder} ...")

    uploaded = []
    for idx, img_path in enumerate(images, start=1):
        res = cloudinary.uploader.upload(
            str(img_path),
            folder="restaurants/the_grill",
            public_id=img_path.stem,
            overwrite=True,
            resource_type="image"
        )
        url = res.get("secure_url") or res.get("url")
        if not url:
            raise RuntimeError(f"Upload failed for {img_path}")
        uploaded.append((img_path.name, url))
        print(f"[{idx}/{len(images)}] -> {url}")

    out_sql = Path(__file__).parent / "insert_the_grill_images.sql"
    with open(out_sql, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by upload_the_grill_images.py\n")
        f.write("-- Insert gallery images for The Grill\n\n")
        for _, url in uploaded:
            f.write(
                "INSERT INTO restaurant_media (restaurant_id, type, url, created_at) "
                f"VALUES ({args.restaurant_id}, 'gallery', '{url.replace(\"'\", \"''\")}', NOW());\n"
            )

    print(f"Generated SQL: {out_sql}")

if __name__ == "__main__":
    main()





